Campo resumo_rubricas
dadosjusbr/armazenador pull request #30
Opened 2023-12-04 16:48 UTC by joellensilva

- Adicionando o campo `resumo_rubricas` a coluna `sumario`

2023-12-08 20:01 UTC, danielfireman requested changes

2023-12-11 18:56 UTC, joellensilva commented on main.go
> +			if slices.Contains(listaRubricas, rubrica) {
Tive um obstáculo (`json: cannot unmarshal string into Go value of type struct {}`), mas acho que cheguei na ideia final.

2023-12-11 18:59 UTC, danielfireman commented on main.go
> +			if slices.Contains(listaRubricas, rubrica) {
Você não deve fazer marshall dessa estrutura de dados. Apenas usar ela como auxiliar.

2023-12-12 12:23 UTC, danielfireman requested changes

2023-12-12 12:23 UTC, danielfireman commented on main.go
> +	// json: cannot unmarshal string into Go value of type struct {}
Como eu te disse via slack, você não precisa fazer unmarshal direto para essa estrutura. Ao invés disso, é ok retornar um `map[string][]string` nessa função.


Você pode criar o `map[string]struct{}` para cada item -- de forma auxiliar --, dentro do método aggregating itens. É normal converter estruturas de dados para as que sejam mais eficientes em determinados usos. Inclusive, isso vai deixar o código mais claro, pois a razão para o uso de uma estrutura mais complexa vai ficar óbvio.

2023-12-13 20:19 UTC, danielfireman approved these changes
Por favor, olhar minhas duas sugestões abaixo (apenas para melhorar desempenho).

2023-12-13 20:19 UTC, danielfireman commented on main.go
> +	itemStruct := make(map[string]map[string]struct{})
```suggestion
	itemStruct := make(map[string]map[string]struct{}, len(items))
```

2023-12-13 20:19 UTC, danielfireman commented on main.go
> +		itemStruct[key] = make(map[string]struct{})
```suggestion
		itemStruct[key] = make(map[string]struct{}, len(values))
```

2023-12-14 17:55 UTC, merged