Adiciona as informações da coleta o índice de transparência calculado
dadosjusbr/armazenador pull request #7
Opened 2021-11-21 18:17 UTC by jeffersonrpn

2021-11-21 18:33 UTC, danielfireman requested changes

2021-11-21 18:33 UTC, danielfireman commented on agency.go
> +	EasinessScore     float64 `json:"max" bson:"easiness_score,omitempty"`
```suggestion
	Score             float64 `json:"score" bson:"score,omitempty"`
	CompletenessScore float64 `json:"completeness_score" bson:"completeness_score,omitempty"`
	EasinessScore     float64 `json:"easiness_score" bson:"easiness_score,omitempty"`
```

2021-11-21 18:33 UTC, danielfireman commented on main.go
> +	var options = map[string]float64{"SUMARIZADO": 0.5, "DETALHADO": 1}
Poderia formatar esse código, por favor?

2021-11-21 18:33 UTC, danielfireman commented on main.go
> +}
Acha que vale a pena adicionar  testes de unidade? Me parecem bem simples de fazer e dão uma boa ideia do funcionamento.

2021-11-23 01:34 UTC, jeffersonrpn commented on main.go
> +	var options = map[string]float64{"SUMARIZADO": 0.5, "DETALHADO": 1}
Apliquei formatação no arquivo todo (não tinha configurado antes).

2021-11-23 01:35 UTC, jeffersonrpn commented on main.go
> +}
Acho válido

2021-11-23 23:01 UTC, danielfireman approved these changes

2021-11-24 14:39 UTC, merged